import CommunitySearch, {searchFocus} from './CommunitySearch';
import MaintenancePanel from './MaintenancePanel';
import ManagerAmenities from './ManagerAmenities';
import ManagerLockers from './ManagerLockers';
import ManagerParcelIntake from './ManagerParcelIntake';
import ManagerParcels from './ManagerParcels';
import CourierManager from './CourierManager';
import ManagerReports from './ManagerReports';
import {SupportSettings} from './Support';
import {ResidentLeaseDocuments} from './LeaseDocuments';
import React, { useEffect, useState } from 'react';
import { api } from './api';
import { AccountSecurity, IssuedLink, RecoveryLinkList, linkStatus } from './AccountAccess';
import './manager-dashboard.css';
const dataOf=e=>Object.fromEntries(new FormData(e.currentTarget));
const date=s=>new Date(s).toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'});
const recovery=id=>`/manager/accounts/${id}/recovery`;
export function ManagerDashboard({user,run,busy,onCode,onSignedOut}) {
 const [section,setSection]=useState('overview'),[rows,setRows]=useState([]),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1);
 const [selected,setSelected]=useState(null),[tab,setTab]=useState('profile'),[events,setEvents]=useState([]),[code,setCode]=useState(''),[notice,setNotice]=useState(''),[issued,setIssued]=useState(null),[creating,setCreating]=useState(false),[ready,setReady]=useState(false);
 const listPath=which=>which==='residents'?'/manager/applications':'/manager/providers';
 async function load(which=section){setReady(false);if(which==='settings')setCode((await api('/manager/invite-code')).code);else if(which==='residents'||which==='providers')setRows(await api(listPath(which)));setReady(true);}
 useEffect(()=>{run(()=>load('overview'));},[]);
 // Search results open the record in its own section; focus tells that section which record to show.
 const [focus,setFocus]=useState(null);
 function openResult(result){const target=searchFocus(result,{PACKAGE:'packages',AMENITY:'amenities',MAINTENANCE:'maintenance'});if(!target)return;setFocus(target.focus);navigate(target.section,true);}
 function navigate(next,keepFocus=false){if(!keepFocus)setFocus(null);setSection(next);setRows([]);setSelected(null);setIssued(null);setQuery('');setStatus('');setPage(1);setCreating(false);setNotice('');run(()=>load(next));}
 async function history(a){const [reviews,rooms,links]=await Promise.all([a.role==='RESIDENT'?api(`/manager/applications/${a.id}/history`):[],a.role==='RESIDENT'?api(`/manager/residents/${a.id}/room-history`):[],api(recovery(a.id))]);setEvents([...reviews.map(e=>({...e,type:'Review',text:`${e.decision}${e.reason?' — '+e.reason:''}`,actor:e.reviewerId,key:'review'+e.id})),...rooms.map(e=>({...e,type:'Room change',text:`${e.oldRoom} → ${e.newRoom}${e.reason?' — '+e.reason:''}`,actor:e.managerId,key:'room'+e.id})),...links.map(e=>({...e,type:'Recovery',text:`${linkStatus(e)} — ${e.verificationNote}`,actor:e.managerId,key:'link'+e.id}))].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)));}
 async function choose(a){await history(a);setSelected(a);setTab('profile');setIssued(null);setNotice('');}
 async function refresh(){const all=await api(listPath(section));setRows(all);setReady(true);if(selected){const a=all.find(x=>x.id===selected.id);setSelected(a||null);if(a)await history(a);}}
 async function update(path,data,message){const a=await api(path,{method:(path.endsWith('/room')||path.endsWith('/service-type'))?'PUT':'POST',data});setSelected(a);await history(a);await load();setNotice(message);}
 function link(result,email){setIssued({...result,email,url:`${location.origin}/recover-link#token=${result.token}`});}
 const recoveryLinks=events.filter(e=>e.type==='Recovery');
 const filtered=rows.filter(a=>(!status||a.status===status)&&[a.name,a.email,a.room].some(v=>(v||'').toLowerCase().includes(query.trim().toLowerCase())));
 const pages=Math.max(1,Math.ceil(filtered.length/8)),current=Math.min(page,pages),visible=filtered.slice((current-1)*8,current*8);
 return <div className="manager-shell"><nav className="manager-nav" aria-label="Manager navigation"><span className="eyebrow">MANAGEMENT</span>{[['overview','Overview'],['search','Search'],['residents','Residents'],['providers','Service providers'],['packages','Packages'],['amenities','Amenities'],['maintenance','Maintenance'],['settings','Community settings'],['security','My account security']].map(([key,label])=><button key={key} aria-current={section===key?'page':undefined} disabled={busy} onClick={()=>navigate(key)}>{label}</button>)}<p>{user.community}</p></nav><div className="manager-content">{notice&&<div className="message" role="status">{notice}</div>}
 {section==='security'?<AccountSecurity user={user} run={run} busy={busy} onCode={onCode} onSignedOut={onSignedOut}/>:
 section==='overview'?<ManagerReports/>:section==='search'?<CommunitySearch user={user} onOpen={openResult}/>:section==='maintenance'?<MaintenancePanel user={user} focus={focus}/>:section==='amenities'?<ManagerAmenities focus={focus}/>:section==='packages'?<><ManagerLockers/><CourierManager scope="manager"/><ManagerParcelIntake/><ManagerParcels focus={focus}/></>:section==='settings'?<><section className="card"><span className="eyebrow">COMMUNITY SETTINGS</span><h2>Registration invite code</h2><p>New registrations use this code. Existing accounts are unaffected and new residents still need approval.</p>{ready&&<form onSubmit={e=>{e.preventDefault();run(async()=>{setCode((await api('/manager/invite-code',{method:'PUT',data:{code}})).code);setNotice('Invite code saved. The previous code no longer accepts registrations.');});}}><label>Current invite code<input value={code} onChange={e=>setCode(e.target.value)} required maxLength={100}/></label><button className="primary" disabled={busy}>Save invite code</button></form>}</section><SupportSettings/></>:
 <><section className="card"><div className="section-head"><div><span className="eyebrow">{section==='residents'?'RESIDENT MANAGEMENT':'SERVICE PARTNERS'}</span><h2>{section==='residents'?'Residents':'Service providers'} <span className="count">{rows.length}</span></h2></div><div className="actions"><button disabled={busy} onClick={()=>run(refresh)}>Refresh</button>{section==='providers'&&<button className="primary" disabled={busy} onClick={()=>setCreating(!creating)}>Create provider</button>}</div></div>
 {creating&&<form className="detail" onSubmit={e=>{e.preventDefault();const data=dataOf(e);run(async()=>{const result=await api('/manager/providers',{method:'POST',data});await load();await choose(result.account);link(result.setup,result.account.email);setCreating(false);setNotice('Account created. Privately send the setup link to the provider.');});}}><h3>Create provider account</h3><label>Name<input name="name" required maxLength={100}/></label><label>Email<input name="email" type="email" required maxLength={254}/></label><label>Service type<select name="providerType" required defaultValue=""><option value="" disabled>Select a service type</option><option value="MAINTENANCE">Maintenance company</option><option value="DELIVERY">Delivery company</option></select></label><p>They choose their own password using a one-time setup link.</p><button disabled={busy}>Create account</button></form>}
 <div className="directory-filters"><label>Search<input type="search" placeholder="Name, email or room" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label>{section==='residents'&&<label>Status<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option>{['PENDING','APPROVED','REJECTED'].map(s=><option key={s}>{s}</option>)}</select></label>}</div>
 {!ready?<p role="status">Loading accounts…</p>:<><div className="table-wrap"><table><thead><tr><th>Name / email</th>{section==='residents'?<th>Room</th>:<th>Service type</th>}<th>Status</th><th>Details</th></tr></thead><tbody>{visible.map(a=><tr key={a.id} className={selected?.id===a.id?'selected-row':''}><td><strong>{a.name}</strong><small>{a.email}</small></td>{section==='residents'?<td>{a.room}</td>:<td>{a.providerType==='MAINTENANCE'?'Maintenance':a.providerType==='DELIVERY'?'Delivery':'Not classified'}</td>}<td><span className={`badge ${a.status}`}>{a.status}</span></td><td><button disabled={busy} aria-label={`Open ${a.name}`} onClick={()=>run(()=>choose(a))}>Open</button></td></tr>)}</tbody></table></div>{!filtered.length&&<p className="empty">No matching accounts. Try another search or filter.</p>}<div className="pagination"><span>{filtered.length} matches · Page {current} of {pages}</span><div className="actions"><button disabled={busy||current===1} onClick={()=>setPage(current-1)}>Previous</button><button disabled={busy||current===pages} onClick={()=>setPage(current+1)}>Next</button></div></div></>}
 </section>
 {selected&&<section className="card person-panel" aria-label="Account details" key={selected.id}><div className="section-head"><div><span className="eyebrow">ACCOUNT DETAILS</span><h2>{selected.name}</h2><p>{selected.email} · {selected.community}</p></div><button disabled={busy} onClick={()=>{setSelected(null);setIssued(null);}}>Close details</button></div>
 {issued&&<IssuedLink issued={issued} links={recoveryLinks} busy={busy} onCopy={()=>run(async()=>{await navigator.clipboard.writeText(issued.url);setNotice('Link copied.');})}/>}
 <div className="person-tabs" role="group" aria-label="Account actions">{[['profile','Profile & review'],...(selected.role==='RESIDENT'?[['room','Change room'],['lease','Lease documents']]:[]),['recovery','Password recovery'],['history','Activity history']].map(([key,label])=><button key={key} disabled={busy} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div>
 {tab==='profile'&&<><p><strong>Status:</strong> {selected.status}{selected.role==='RESIDENT'&&<> · <strong>Room:</strong> {selected.room}</>}</p>{selected.role==='PROVIDER'&&<form key={`${selected.id}-${selected.providerType}`} onSubmit={e=>{e.preventDefault();const data=dataOf(e);run(()=>update(`/manager/providers/${selected.id}/service-type`,data,'Service type updated. The provider sees the matching workspace after refresh.'));}}><label>Service type<select name="providerType" required defaultValue={selected.providerType||''}><option value="" disabled>Select a service type</option><option value="MAINTENANCE">Maintenance company</option><option value="DELIVERY">Delivery company</option></select></label><p>Maintenance companies receive repair assignments. Delivery companies use the package delivery desk.</p><button disabled={busy} className="primary">Save service type</button></form>}<p>Recovery code: {selected.hasRecoveryCode?'Created':'Not created yet'}</p>{selected.rejectionReason&&<p>Rejection reason: {selected.rejectionReason}</p>}{selected.role==='RESIDENT'&&selected.status==='PENDING'&&<form onSubmit={e=>{e.preventDefault();const data=dataOf(e);const decision=e.nativeEvent.submitter.value;run(()=>update(`/manager/applications/${selected.id}/review`,{status:decision,reason:data.reason},'Review saved.'));}}><p>Verify the name and room against resident records before reviewing.</p><label>Reason (required for rejection)<textarea name="reason" maxLength={1000}/></label><div className="actions"><button disabled={busy} value="APPROVED" className="primary">Approve</button><button disabled={busy} value="REJECTED">Reject with reason</button></div></form>}</>}
 {tab==='lease'&&selected.role==='RESIDENT'&&<ResidentLeaseDocuments resident={selected}/>}
 {tab==='room'&&<form onSubmit={e=>{e.preventDefault();const data=dataOf(e);run(()=>update(`/manager/residents/${selected.id}/room`,data,'Room updated. Approval status is unchanged.'));}}><p>Current room: <strong>{selected.room}</strong>. This will not change approval status.</p><label>New room / unit<input name="room" required maxLength={30}/></label><label>Reason for change (optional)<textarea name="reason" maxLength={1000}/></label><button disabled={busy} className="primary">Save room change</button></form>}
 {tab==='recovery'&&<><p>Verify identity before generating a link. Knowing an email address alone is not proof of identity.</p><form onSubmit={e=>{e.preventDefault();const data=dataOf(e);run(async()=>{const result=await api(recovery(selected.id),{method:'POST',data:{note:data.note,verified:data.verified==='on'}});link(result,selected.email);await history(selected);setNotice('Recovery link created. Previous unused links are revoked.');});}}><label>Verification notes<textarea name="note" required maxLength={1000}/></label><label className="check-label"><input name="verified" type="checkbox" required/>I have verified the account owner’s identity.</label><button disabled={busy} className="primary">Create 30-minute recovery link</button></form><button disabled={busy} onClick={()=>run(async()=>{await api(recovery(selected.id),{method:'DELETE'});await history(selected);setNotice('Unused links revoked.');})}>Revoke unused links</button><div className="section-head"><h3>Recovery links</h3><button disabled={busy} onClick={()=>run(()=>history(selected))}>Refresh</button></div><RecoveryLinkList links={recoveryLinks}/></>}
 {tab==='history'&&<><div className="section-head"><h3>Account activity</h3><button disabled={busy} onClick={()=>run(()=>history(selected))}>Refresh history</button></div><p>Review, room-change and recovery records for this person.</p>{events.length?<ol className="activity-list">{events.map(e=><li key={e.key}><strong>{e.type}</strong><p>{e.text}</p><small>{date(e.createdAt)} · Manager #{e.actor}</small></li>)}</ol>:<p>No recorded activity.</p>}</>}
 </section>}
 </>}
 </div></div>;
}
