import {portalUrl} from './api';
import React,{useEffect,useState} from 'react';
import {api} from './api';
import IdleSignOut from './IdleSignOut';
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);
/** Bills for a signed-in, approved resident or manager; used by the Payments page and the resident's My Account. */
export function PaymentsPanel({user}){
 const [confirming,setConfirming]=useState(false);
 const [rows,setRows]=useState([]),[residents,setResidents]=useState([]),[busy,setBusy]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[filter,setFilter]=useState(''),[selected,setSelected]=useState(null);
 async function load(){const bills=await api('/payments');if(!Array.isArray(bills))throw new Error('Unable to load bills. Please refresh and try again.');setRows(bills);setSelected(old=>old?bills.find(b=>b.id===old.id)||null:null);if(user.role==='MANAGER')setResidents(await api('/payments/residents'));}
 async function run(fn){setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e.status===401?'Sign in on the home page, then refresh this page.':e.message);}finally{setBusy(false);}}
 useEffect(()=>{run(load);},[]); // eslint-disable-line react-hooks/exhaustive-deps
 const total=rows.filter(b=>b.status==='UNPAID').reduce((sum,b)=>sum+Math.round(Number(b.amount)*100),0)/100;
 return <>{error&&<div className="message error" role="alert">{error}</div>}{notice&&<div className="message" role="status">{notice}</div>}<button disabled={busy} onClick={()=>run(load)}>Refresh</button>{busy&&<p role="status">Loading…</p>}
 {user.role==='MANAGER'&&<section className="card"><h2>Create a bill</h2><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));run(async()=>{await api('/payments',{method:'POST',data:{...data,residentId:Number(data.residentId)}});form.reset();await load();setNotice('Bill created. The resident can view it in My Account.');});}}><fieldset disabled={busy} style={{border:0,padding:0}}><label>Resident<select name="residentId" required defaultValue=""><option value="" disabled>Select a resident</option>{residents.map(r=><option key={r.id} value={r.id}>{r.name} · Room {r.room}</option>)}</select></label><label>Title<input name="title" required maxLength={100}/></label><label>Description<textarea name="description" maxLength={1000}/></label><div className="grid"><label>Amount (USD)<input name="amount" type="number" min="0.01" max="9999999.99" step="0.01" required/></label><label>Due date (YYYY-MM-DD, Pacific time)<input name="dueDate" placeholder="2026-10-01" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" required/></label></div><button className="primary" disabled={!residents.length}>Create bill</button></fieldset></form></section>}
 <section className="card"><div className="section-head"><h2>{user.role==='MANAGER'?'Community bills':'My bills'}</h2><strong>Unpaid: {money(total)}</strong></div><label>Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All bills</option><option value="UNPAID">Unpaid</option><option value="PAID">Paid / payment history</option></select></label><div className="table-wrap"><table><thead><tr><th>Bill</th><th>Amount</th><th>Due date</th><th>Status</th><th>Details</th></tr></thead><tbody>{rows.filter(b=>!filter||b.status===filter).map(b=><tr key={b.id}><td><strong>{b.title}</strong>{user.role==='MANAGER'&&<p>{b.residentName} · Room {b.room}</p>}</td><td>{money(b.amount)}</td><td>{b.dueDate}</td><td><span className="badge">{b.status}</span></td><td><button disabled={busy} onClick={()=>{setSelected(b);setConfirming(false);}}>View details</button></td></tr>)}</tbody></table></div>{!rows.filter(b=>!filter||b.status===filter).length&&<p className="empty">No bills in this view.</p>}</section>
 {selected&&<section className="card"><div className="section-head"><h2>{selected.title}</h2><button disabled={busy} onClick={()=>{setSelected(null);setConfirming(false);}}>Close details</button></div><p style={{whiteSpace:'pre-wrap'}}>{selected.description}</p><p>{money(selected.amount)} · Due {selected.dueDate}</p>{selected.status==='PAID'?<><p>Simulated payment completed: {new Date(selected.paidAt).toLocaleString('en-US')}</p><p style={{overflowWrap:'anywhere'}}>Receipt: {selected.receiptNumber}</p><p>This is a demo receipt, not proof of a real payment.</p></>:user.role==='RESIDENT'&&<div>{!confirming?<button className="primary" disabled={busy} onClick={()=>setConfirming(true)}>Simulate payment</button>:<div className="help-box"><p>Confirm simulated payment of {money(selected.amount)}? No real money will be charged.</p><div className="actions"><button disabled={busy} onClick={()=>setConfirming(false)}>Cancel</button><button className="primary" disabled={busy} onClick={()=>run(async()=>{const result=await api(`/payments/${selected.id}/pay`,{method:'POST',data:{confirmed:true}});await load();setSelected(result);setConfirming(false);setNotice('Demo payment recorded. No real charge was made.');})}>Confirm demo payment</button></div></div>}</div>}</section>}</>;
}
export default function Payments(){
 const [user,setUser]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{api('/auth/me').then(setUser).catch(e=>setError(e.status===401?'Sign in on the home page, then refresh this page.':e.message)).finally(()=>setLoading(false));},[]);
 const allowed=user?.status==='APPROVED'&&['MANAGER','RESIDENT'].includes(user?.role);
 return <><header><a className="brand" href={portalUrl("/")}>CP <span>Community Property <small>MANAGEMENT SYSTEM</small></span></a></header><main><div className="intro"><span className="eyebrow">BILLING</span><h1>Payments</h1><p>Demo payment — no real charge. No card or bank details are collected.</p></div>{error&&<div className="message error" role="alert">{error}</div>}{loading&&<p role="status">Loading…</p>}
 {allowed&&<PaymentsPanel user={user}/>}{user&&!allowed&&<div className="message error" role="alert">Payments are available to approved residents and managers.</div>}
 </main>{user&&<IdleSignOut/>}</>;
}
